const productsData = [
{category: "Women", name: "Kali Wool and Silk Coat", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/92/P00664926.jpg", brand: "The Row", description: "The Kali coat is made from fine wool and silk with a luxurious drape and an A-line silhouette defined by fabric-covered buttons in the front. Made in Italy.", stock: 5, price: "$4250USD"},
{category: "Women", name: "Crêpe Blazer", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/38/P00302831.jpg", brand: "Alexander McQueen", description: "Crafted in Italy from structured crêpe, the suiting separate nips in at the waist, creating a fitted silhouette that's enhanced by the darted bust and angled flap pockets at the sides. The peak lapels and padded shoulders serve to sharpen the angles of the overall look.", stock: 5, price: "$1995USD"},
{category: "Women", name: "Isabel Mid-Rise Slim Virgin Wool Pants", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/ab/P00702083.jpg", brand: "Gabriela Hearst", description: "Made in Italy from virgin wool, this black pair of trousers is designed with a classic mid-rise waist and press pleated slim-leg fit.", stock: 5, price: "$776USD"},
{category: "Women", name: "Ribbed-knit wool-blend pencil skirt", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/62/P00696026.jpg", brand: "Tom Ford", description: "Crafted in Italy from wool-blend yarn, this pencil skirt is knitted with ribbed stitches. Its knee-length design stretches to fit.", stock: 5, price: "$850USD"},
{category: "Women", name: "Silk Shirt", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/33/P00696054.jpg", brand: "Valentino", description: "Crafted in Italy from pure silk, this white shirt has an elegant self-tie neckline and a relaxed fit.", stock: 5, price: "$1900USD"},
{category: "Women", name: "Cashmere and Silk T-Shirt", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/cb/P00696119.jpg", brand: "Tom Ford", description: "Crafted in Italy from a cashmere and silk blend with a fitted silhouette.", stock: 10, price: "$1190USD"},
{category: "Women", name: "Maritza Layered Cotton Maxi Dress", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/7c/P00713176.jpg", brand: "The Row", description: "The Maritza T-shirt maxi length dress is designed with a separate layer, allowing for versatile styling options or a layered look. Crafted in Italy from organically cultivated cotton jersey.", stock: 10, price: "$890USD"},
{category: "Women", name: "Kate Medium Leather Shoulder Bag", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/1c/P00361038.jpg", brand: "Saint Laurent", description: "The Kate bag, with its glossy golden-hued YSL monogram and sleek silhouette, dangles from a shiny chain strap. Crafted in Italy from calf skin, it closes with magnetic fastening to complement the envelope design.", stock: 5, price: "$2190"},
{category: "Women", name: "The Bow Large Leather Tote Bag", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/6b/P00697916.jpg", brand: "Alexander McQueen", description: "McQueen's large tote bag has a suede-lined interior and a detachable zip pouch with a card pocket. Crafted in Italy from smooth cow leather.", stock: 5, price: "$2290USD"},
{category: "Women", name: "Tabi Leather Ballet Flats", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/fb/P00591250_d3.jpg", brand: "Maison Margiela", description: "Iconic. Immediately recognizable. Crafted in Italy from smooth lambskin leather.", stock: 8, price: "$650USD"},
{category: "Women", name: "Leather Platform Ankle Boots", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/be/P00695532.jpg", brand: "Alexander McQueen", description: "McQueen's platform boots offer a polished take on the silhouette. Crafted in Italy from calfskin leather.", stock: 8, price: "$1390USD"},

{category: "Men", name: "William Belted Coat", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/69/P00654781.jpg", brand: "The Row", description: "Made in Italy, from a fine blend of wool and mohair, the William coat has a structured silhouette that can be further defined at the belted waist.", stock: 5, price: "$3450USD"},
{category: "Men", name: "Double-Breasted Wool-Blend Blazer", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/40/P00613428.jpg", brand: "Gucci", description: "Finished with a wide notched lapel, this blazer offers a sleek, double-breasted silhouette. It is Italian-crafted from a soft blend of wool and mohair, and is detailed with the label's logo patch appliquéd on the sleeve.", stock: 5, price: "$3600USD"},
{category: "Men", name: "Wool-Blend Wide-leg Pants", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/e0/P00613432.jpg", brand: "Gucci", description: "Tailored in Italy from a blend of wool and mohair wool, these have a wide-leg silhouette with seam detailing, and an internal curtained waistband.", stock: 5, price: "$1300USD"},
{category: "Men", name: "Grosgrain Armband Shirt", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/9a/P00501847.jpg", brand: "Thom Browne", description: "This classic button-down style shirt is woven, in Italy, from oxford cotton and features the brand's signature tricolor grosgrain armband.", stock: 8, price: "$450USD"},
{category: "Men", name: "Dolores Cotton Jersey Maxi Dress", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/87/P00609558.jpg", brand: "", description: "Made in Italy, from pure cotton jersey, this t-shirt dress falls into a straight, column silhouette with the label's signature seam down the center of the back.", stock: 8, price: "$620USD"},
{category: "Men", name: "Cashmere Hooded Sweatshirt", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/12/P00649751.jpg", brand: "Alexander McQueen", description: "This hooded sweatshirt is crafted in Italy from cashmere. It offers a cozy fit and has a drawstring hood and kangaroo pocket on the front.", stock: 8, price: "$1240USD"},
{category: "Men", name: "Antigona Leather Crossbody Bag", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/47/P00550963.jpg", brand: "Givenchy", description: "A small crossbody-style bag which can be worn across the chest, and is crafted in Italy from smooth black leather featuring a fabric jacquard strap, and silver-tone hardware accents.", stock: 8, price: "$1395USD"},
{category: "Men", name: "Leather Tote Bag", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/d8/P00511560.jpg", brand: "Tom Ford", description: "This large tote bag is crafted in Italy from smooth black leather. Enhanced by gold-tone T hardware, it comes with a detachable strap and top handles.", stock: 5, price: "$5390USD"},
{category: "Men", name: "Leather Boots", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/db/P00619442_d2.jpg", brand: "Rick Owens", description: "With smooth leather uppers, these black ankle boots are enhanced by chunky rubber soles, have elasticated side panels, and a back pull tab for an easy slip-on. Crafted in Italy.", stock: 8, price: "$1295USD"},
{category: "Men", name: "Defender Sneakers", image: "https://img.mytheresa.com/1088/1088/66/jpeg/catalog/product/ff/P00700934_d2.jpg", brand: "Balenciaga", description: "These futuristic sneakers have mesh-trimmed nylon uppers with conversation-starting arched embossed soles. Crafted in China.", stock: 10, price: "$1150USD"}
];

module.exports = productsData;